.github/CODEOWNERS
Not entirely sure. We're still trying to figure this out. CODEOWNERS are required to ship a review, but there isn't a file yet.
Issue Number: PYT-899 (internal)
Four code owners will be added for the entire repo. Once the project is fully open sourced we will add more.
=> PYT-899 Initial migration: Create codeowners file

.github/workflows/pre-commit.yml, common/setup.py, libs/setup.py, platform/setup.py, platform/src/test/python/dlpx/virtualization/test_plugin.py, tools/src/test/python/dlpx/virtualization/_internal/test_package_util.py
Issue Number: PYT-900
- Added Github Action for pre-commit that runs unit tests on common, libs, platform, tools projects of virtualization-sdk. It also lints tools project as of now. linting for other projects can be added later.
- Job for checking format of projects is added but commented out so that it can be enabled once the formatting is fixed.
- setup.py files are modified to use the dvp-api dependency from test pypi as artifactory cannot be used by github actions
- Fixed an existing testcase that was failing in ubuntu environment
=> Fixes PYT-900 : Initial migration: Write pre commit action

tools/setup.py, tools/src/test/python/dlpx/virtualization/_internal/test_cli.py
After Click 7.1 release (March 9, 2020), the CLI tests started failing with errors of this sort:
```
E         - Try 'delphix-sdk build -h' for help.
E         ?     ^                    ^
E         + Try "delphix-sdk build -h" for help.
E         ?     ^   
```
It looks like the click CLI now outputs single rather than double quotes in its error messages. This is related to [the following commit](https://github.com/pallets/click/commit/718485be48263056e7036ea9a60ce11b47e2fc26#) that did manual cleanup before the release. The commit has been shipped in versions 7.1 and 7.1.1.
Modify CLI tests to expect single rather than double quotes.
=> Fix CLI tests after Click 7.1 release

.bumpversion.cfg, common/src/main/python/dlpx/virtualization/common/VERSION, dvp/src/main/python/dlpx/virtualization/VERSION, libs/src/main/python/dlpx/virtualization/libs/VERSION, platform/src/main/python/dlpx/virtualization/platform/VERSION, tools/src/main/python/dlpx/virtualization/_internal/VERSION, tools/src/main/python/dlpx/virtualization/_internal/cli.py, tools/src/main/python/dlpx/virtualization/_internal/commands/upload.py, tools/src/main/python/dlpx/virtualization/_internal/delphix_client.py, tools/src/main/python/dlpx/virtualization/_internal/exceptions.py, tools/src/test/python/dlpx/virtualization/_internal/commands/test_build.py, tools/src/test/python/dlpx/virtualization/_internal/commands/test_delphix_client.py, tools/src/test/python/dlpx/virtualization/_internal/commands/test_upload.py, tools/src/test/python/dlpx/virtualization/_internal/test_cli.py, tools/src/test/python/dlpx/virtualization/_internal/test_package_util.py, tools/src/test/python/dlpx/virtualization/_internal/test_plugin_importer.py
The dvp upload command issues an upload job to a Delphix Engine but does not wait for the upload to complete before returning. This can be problematic for both testing and end-users since we can't tell whether the upload job finished successfully or not.
Introduce a wait flag in the dvp upload command that waits for the upload job to complete. We query the upload action and job every 5 seconds until the job succeeds, fails, or times out (60 min).
=> PYT-1103 No error displayed by the dvp upload command when file upload job fails

CONTRIBUTING.md, README-dev.md, tools/README-dev.md
The README was a little outdated, had mentions of the old Gradle build, and few errors.
README-dev.md describes the new development workflow.
=> Update the README and contribution guidelines to reflect the new development workflow

tools/src/main/python/dlpx/virtualization/_internal/cli.py
dvp init -s staged fails on windows
Issue Number: 96
dvp init -s staged successful on windows
=> Fixes #96 dvp init hitting TypeError on Windows10

.bumpversion.cfg, common/src/main/python/dlpx/virtualization/common/VERSION, dvp/src/main/python/dlpx/virtualization/VERSION, libs/src/main/python/dlpx/virtualization/libs/VERSION, platform/src/main/python/dlpx/virtualization/platform/VERSION, tools/src/main/python/dlpx/virtualization/_internal/VERSION, tools/src/main/python/dlpx/virtualization/_internal/commands/build.py, tools/src/main/python/dlpx/virtualization/_internal/validation_schemas/plugin_config_schema.json, tools/src/main/python/dlpx/virtualization/_internal/validation_schemas/plugin_config_schema_no_id_validation.json, tools/src/test/python/dlpx/virtualization/_internal/commands/test_build.py, tools/src/test/python/dlpx/virtualization/_internal/conftest.py, tools/src/test/python/dlpx/virtualization/_internal/test_package_util.py, tools/src/test/python/dlpx/virtualization/_internal/test_plugin_validator.py
dvp build will not expect a luaName field in the plugin config
dvp build will add the luaName property into the upload artifact if it exists
=> PYT-868 Lua to Python - Change plugin config to expect optional lua name

.github/workflows/pre-commit.yml
Linting jobs kicked off by GitHub actions use incorrect test directory in the `tools` package: 
`test/main/python`. This results in failures of this kind:
```Run python -m flake8 test/main/python --max-line-length 88
python -m flake8 test/main/python --max-line-length 88
shell: /bin/bash -e {0}
env:
pythonLocation: /opt/hostedtoolcache/Python/2.7.18/x64
test/main/python:0:1: E902 IOError: [Errno 2] No such file or directory: 'test/main/python'
##[error]Process completed with exit code 1
```
see https://github.com/delphix/virtualization-sdk/pull/122/checks
Fix the linting command to target the correct directory: `src/test/python`.
=> Fix linting job for tools

.github/workflows/pre-commit.yml, tools/src/main/python/dlpx/virtualization/_internal/file_util.py, tools/src/main/python/dlpx/virtualization/_internal/plugin_importer.py, tools/src/test/python/dlpx/virtualization/_internal/commands/test_build.py, tools/src/test/python/dlpx/virtualization/_internal/commands/test_codegen.py, tools/src/test/python/dlpx/virtualization/_internal/test_file_util.py, tools/src/test/python/dlpx/virtualization/_internal/test_package_util.py, tools/src/test/python/dlpx/virtualization/_internal/test_plugin_dependency_util.py, tools/src/test/python/dlpx/virtualization/_internal/test_plugin_importer.py, tools/src/test/python/dlpx/virtualization/_internal/test_schema_validator.py
Fixing unit tests on windows
Issue Number: 10
- Added github action for running unitests on windows
=> Fixes #10 Fix the test issues of virtualization sdk on windows

tools/src/test/python/dlpx/virtualization/_internal/commands/test_build.py, tools/src/test/python/dlpx/virtualization/_internal/commands/test_codegen.py, tools/src/test/python/dlpx/virtualization/_internal/commands/test_delphix_client.py, tools/src/test/python/dlpx/virtualization/_internal/conftest.py, tools/src/test/python/dlpx/virtualization/_internal/test_file_util.py, tools/src/test/python/dlpx/virtualization/_internal/test_plugin_dependency_util.py, tools/src/test/python/dlpx/virtualization/_internal/test_plugin_importer.py, tools/src/test/python/dlpx/virtualization/_internal/test_plugin_validator.py, tools/src/test/python/dlpx/virtualization/_internal/test_schema_validator.py
The linter GitHub action started failing with the following errors:
```Run python -m flake8 src/test/python --max-line-length 88
src/test/python/dlpx/virtualization/_internal/test_file_util.py:38:89: E501 line too long (92 > 88 characters)
src/test/python/dlpx/virtualization/_internal/test_file_util.py:89:89: E501 line too long (102 > 88 characters)
src/test/python/dlpx/virtualization/_internal/test_plugin_importer.py:47:82: W291 trailing whitespace
src/test/python/dlpx/virtualization/_internal/test_plugin_importer.py:50:1: W293 blank line contains whitespace
src/test/python/dlpx/virtualization/_internal/test_plugin_importer.py:51:44: W291 trailing whitespace …
```
=> Fix linting and formatting issues in the tools package

.github/workflows/publish-python-packages.yml
Python packages are built and published to Test PyPi manually.
This PR adds a GitHub action with the following behavior: when the dvp VERSION file (`dvp/src/main/python/dlpx/virtualization/VERSION`) is changed on master, develop, or release branch, we will build all Python packages and publish them to Test PyPi.
I have tested this action on my fork. I have verified that the action connects and tries to upload to Test PyPi (see https://github.com/fdrozdowski/virtualization-sdk/runs/759631255?check_suite_focus=true):
```
Uploading distributions to https://test.pypi.org/legacy/
Uploading dvp_common-2.1.0.dev2-py2-none-any.whl
0%|          | 0.00/14.1k [00:00<?, ?B/s]
HTTPError: …
```
=> Fixes #74 CI/CD: Write release GH Action: build and publish

.github/workflows/publish-docs.yml, docs/Pipfile, docs/Pipfile.lock, docs/readme.md
GitHub action for building and publishing documentation to GitHub Pages.
Currently, we have to check out the latest documentation branch, build the documentation, and publish the static contents to the `gh-pages` branch.
We introduce a new GitHub workflow that is kicked off on any `docs/*` branch if `docs/*` path has been modified and if a `docs/*` branch is created. The workflow checks if the branch it's running on is the latest documentation branch (docs/x.y.z where x.y.z is the highest available version). If that check passes, we install `pipenv`, install the dependencies for building documentation, build the documentation, and publish the static contents to the `gh-pages` …
=> Fixes #73 CI/CD: Write release GH Action: publish docs

tools/src/test/python/dlpx/virtualization/_internal/commands/test_build.py, tools/src/test/python/dlpx/virtualization/_internal/commands/test_initialize.py, tools/src/test/python/dlpx/virtualization/_internal/fake_plugin/direct/bad_syntax.py, tools/src/test/python/dlpx/virtualization/_internal/fake_plugin/direct/import_error.py, tools/src/test/python/dlpx/virtualization/_internal/fake_plugin/direct/undefined_name.py, tools/src/test/python/dlpx/virtualization/_internal/test_cli.py, tools/src/test/python/dlpx/virtualization/_internal/test_plugin_importer.py, tools/src/test/python/dlpx/virtualization/_internal/test_plugin_validator.py
There are Blackbox test cases(aka qa-gate) which test the dvp commands and various options/parameters etc.
Moving some those test cases from Blackbox to the SDK repo since they don't really require a delphix engine.
Issue Number: N/A
-
-
-
=> Fixes #253 Move some CLI tests from Blackbox to SDK repo

docs/docs/References/Schemas.md
No mention of `default`
Added a warning about misinterpreting JSON schema's `default` keyword.  (Also fixed a couple of incorrect quote characters)
=> Fixes #258 Add clearer doc for JSON schema's default keyword

platform/src/test/python/dlpx/virtualization/test_plugin.py
Adding a new testcase for the initialize user method to test the scenario where it returns None.
Issue Number: N/A
-
-
-
=> Fixes #262 Add test_virtual_initialize_return_none

.github/workflows/publish-docs.yml
The `Publishing docs to GitHub pages` GitHub action has been failing for a couple months with this error message:
The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to true. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Set the `CURRENT_BRANCH` and `LATEST_DOCS_BRANCH` environment variables without using `set-env` as recommended by GitHub.
I was able to test by pushing the changes to my VSDK fork and creating a branch from that fork.
Clean test run here: …
=> Publishing docs to GitHub pages fails because set-env has been deprecated

docs/docs/Best_Practices/Sensitive_Data.md, docs/docs/References/Classes.md, docs/docs/References/Platform_Libraries.md, docs/docs/References/Schemas.md, docs/docs/Versioning_And_Upgrade/Upgrade.md
Documents the new credentials-supplier feature that lets users choose between entering passwords/keys directly or linking to a password vault.
Preview: https://rasantel.github.io/virtualization-sdk/
Fixes #267 .
=> Document password vault support for VSDK plugins

docs/docs/Building_Your_First_Plugin/Initial_Setup.md
- [ x ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
Docs typo fix
- [ x ] Documentation content changes
Exmaple contains WINDOWS, should be UNIX
- [ x ] No
git diff showed that the last line had changed, the source had
\ No newline at end of file
but I wasn't able to achieve that with my text editor
=> Correct Typo in Example, it should be UNIX not WINDOWS

.github/workflows/publish-docs.yml
Docs deployment is currently broken as the permissions for the GITHUB_TOKEN seem to have changed. 
Our org seems to have the "restricted" default:
https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token
The publish-docs github action fails with:
>  /usr/bin/git push origin gh-pages
>  remote: Permission to delphix/virtualization-sdk.git denied to github-actions[bot].
>  fatal: unable to access 'https://github.com/delphix/virtualization-sdk.git/': The requested URL returned error: 403
>  Error: Action failed with "The process '/usr/bin/git' failed with exit code 128"
https://github.com/delphix/virtualization-sdk/runs/2878474054
Use a deploy_token instead.
Created a deploy key in my personal fork and tested the docs deployment.
Followed the …
=> Update publish-docs to use a deploy_key

docs/mkdocs.yml
Cherry-pick the following commit from `docs/3.1.0` to develop
```
commit 16b2559abc573de556cfa9520c9f6bb20f9d128f
Author: Tom Walsh <61519496+mothslaw@users.noreply.github.com>
Date:   Mon Mar 15 15:31:12 2021 -0400
Fix version number in doc header (#358)
```
=> Fix version number in doc header (#358)

.github/workflows/publish-docs.yml
Clean cherry-pick of the following commit from `docs/3.1.0` to `develop`
```
commit c1ee1b4214cb5c09dc15b1abd815e9d44909a5b3 (upstream/docs/3.1.0)
Author: ankursarin <ankursarin@gmail.com>
Date:   Fri Sep 10 09:28:07 2021 -0700
Update SDK Docs deployment to use a deploy_key (#392)
```
=> Update SDK Docs deployment to use a deploy_key (#392)

.github/workflows/pre-commit.yml, README.md, docs/CONTRIBUTING.md, docs/docs/Best_Practices/Code_Sharing.md, docs/docs/Best_Practices/Managing_Scripts_For_Remote_Execution.md, docs/docs/Best_Practices/User_Visible_Errors.md, docs/docs/Getting_Started.md, docs/docs/References/Decorators.md, docs/docs/References/Logging.md, docs/docs/References/Platform_Libraries.md, docs/docs/References/Plugin_Config.md, docs/docs/References/Version_Compatibility.md, docs/docs/Release_Notes/4.0.0/.pages, docs/docs/Release_Notes/4.0.0/4.0.0.md, docs/docs/Release_Notes/4.0.0/4.0.0_Breaking_Changes.md, docs/mkdocs.yml
This diff updates the docs to reflect the transition to Python3. Included a new Version Compatibility page for vSDK -> Delphix Engine and vSDK -> Python version mapping. Other changes are mostly updating links and replacing `pkgutil.get_data` with Python 3's `importlib.resources.read_text`, as well as some other small updates.
Also had to update the actions for testing on Python 2.7 as it seems `macos-latest` has now reached a version that doesn't support Python 2.7 at all. Set this subset of tests to run on macos-10.15.
Also replaced references to Jas Sumal with Ryan Fowler as Jas left Delphix awhile back.
=> CP-6694 Update docs for SDK 4.0.0

docs/docs/Best_Practices/Message_Limits.md
This pull request updates the VSDK documentation with the new gRPC message limit for these two use cases:
1. Inputs sent from the plugin to the engine, as arguments to a [Platform library](/References/Platform_Libraries.md) function. For example, the `message` field that is passed to `logger.debug`.
2. Outputs sent back from the engine to the plugin, as the return values from Platform Library functions. For example, the `stdout` resulting from a call to `libs.run_bash`.
We increased the limit from 32MiB to 192MiB
=> Update documentation with new gRPC message limits #411

tools/src/main/python/dlpx/virtualization/_internal/settings.cfg, tools/src/test/python/dlpx/virtualization/_internal/conftest.py, tools/src/test/python/dlpx/virtualization/_internal/test_package_util.py
As the GitFlow is changing for app-gate and qa-gate, develop will now point to latest version of released Delphix Engine API version which is 1.11.16. This will keep develop and master branch in sync.
=> DLPX-83062 Update engine version to 1.11.16 in develop branch

.github/workflows/publish-python-packages.yml, bin/build_project.sh, common/requirements.txt, common/setup.cfg, common/setup.py, dvp/requirements.txt, dvp/setup.py, libs/requirements.txt, libs/setup.cfg, libs/setup.py, platform/requirements.txt, platform/setup.cfg, platform/setup.py, tools/requirements.txt, tools/setup.py, tools/src/main/python/dlpx/virtualization/_internal/plugin_validator.py, tools/src/test/python/dlpx/virtualization/_internal/test_plugin_validator.py
There are around 40 PRs opened by dependentBot to bump up the dependencies version. Also, some dependencies in our setup.py uses `>=` dependencies for example `flake8 >= 3.6` which can cause some unknown errors in case dependencies releases a new version.
Recently, flake8 released 6.0.0 version which started causing `dvp build` to fail with `'Manager' object has no attribute 'checkers'`, as flake8 6.0.0 has made changes to manager package.
The exact cause of the issue is `plugin_validator.py` in `tools` package (line no. 213) where we try to access `checkers` object @`style_guide._application.file_checker_manager.checkers`.
As flake8 6.0.0 has removed `checkers` and started using `result` object, the issue occurred.
1. Change all `>=` to `>=, <` or `==` in setup.py files of all packages. …
=> DLPX-84163 Update all the greater than equal to (>=) dependencies in setup.py and requirements.txt files of dvp packages to equal to(==)

common/setup.py, docs/docs/References/Glossary.md, docs/docs/References/Schemas.md, docs/docs/References/Version_Compatibility.md, docs/docs/Versioning_And_Upgrade/Replication.md, docs/readme.md, libs/setup.py, platform/setup.py, tools/src/test/python/dlpx/virtualization/_internal/test_package_util.py
**Updating the dvp-api version to 1.8.0.dev0 from 1.7.1.dev0.**
As we updated dvp-api to 1.7.1.dev0, it does not restrict users to upload the plugins developed using the dvp-api 1.7.1.dev0 on unsupported Delphix engine as we do not check for patch version changes.
The problem would be that a plugin supporting multinode changes will start failing on older Delphix engine.
Updating the dvp-api to 1.8.0.dev0 helps restrict users to upload the plugins as we do check for minor and major version changes.
**Manual Testing**
Uploaded the plugin built on the changes to 
- Latest engine (Failure message observed)
- Latest engine with Multinode changes (MAX_SUPPORTED_VERSION is 1.8.0) (Successfully Uploaded)
**Automation Testing**
AppData_Python_Module - …
=> CP-10003 Update dvp-api version to 1.8.0.dev0 in libs, platform and common modules

docs/Pipfile, docs/Pipfile.lock, docs/mkdocs.yml, linkcheck-skip.txt, tools/setup.py
A High Severity alert was raised by DependenBot as per PR - https://github.com/delphix/virtualization-sdk/pull/462, which asks to update the `Pymdown-extensions` to `10.0.0`.
Updated all the dependencies to the latest version. It includes
- mkdocs
- mkdocs-material
- markdown-include
- mkdocs-awesome-pages-plugin
Updating the `mkdocs-material` to latest version required us to update the `mkdocs.yml` also as the primary Delphix color started breaking. We do provide `custom` palette for Delphix, but we were not mentioning it specifically anywhere. The change include mentioning the custom palette in `mkdocs.yml`.
More Info - https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=pale#customization
All the changes are available at - …
=> CP-10040 High Severity alert on Pymdown-extensions versions lesser than 10.0

docs/docs/References/Version_Compatibility.md
Release Jython Removal documentation changes. 
Raised after comparing master to docs branch. A clean cherry pick.
=> CP-10628 Release Jython Removal Documentation changes.

common/setup.py, libs/setup.py, platform/setup.py, tools/src/test/python/dlpx/virtualization/_internal/test_package_util.py
Updating the version to 1.9.0.dev0 as dlpx-app-gate code is dependent on version lesser than 2.0.0
virtualization-sdk - https://selfservice-jenkins.eng-tools-prd.aws.delphixcloud.com/job/blackbox-self-service/154115/consoleFull
=> CP-11885 Update the dvp-api version to 1.9.0 in virtualization code

tools/src/main/python/dlpx/virtualization/_internal/validation_schemas/plugin_schema.json, tools/src/test/python/dlpx/virtualization/_internal/test_schema_validator.py
DVP Record size schema validation changes for setting ZFS record size
[CP-12230](https://perforce.atlassian.net/browse/CP-12230)
Added schema validation in plugin_schema.json to check if the field "recordSizeInKB" is of type "integer".
Explanation of the change:
Here in this case the normal validation like below won't work :
`"recordSizeInKB": { 
"type" : "integer" 
}`
In this case, we need to retrieve the properties of recordSizeInKB to get the type and then validate it.
- In order to validate if the field "recordSizeInKB" is of type "integer", we have to first retrieve the "properties" field of "linkedSourceDefinition" and "virtualSourceDefinition". This is because the "recordSizeInKB" field needs to be listed within the "properties" field of "linkedSourceDefinition" and …
=> CP-12230 DVP Record size validation changes for setting ZFS record size

docs/docs/Getting_Started.md
Fixes a typo in the property name, correcting `dlpx.virtulization.platform` to `dlpx.virtualization.platform`
**UI Preview:**
Current: https://developer.delphix.com/Getting_Started/
After Change: https://vimleshmishra.github.io/virtualization-sdk/Getting_Started/
=> DLPXDOC-3433 Typo in instructions for virtualization sdk docs
